# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end


platform :android do
  desc "fastlane example"
  lane :distribute do
    gradle(
      task: "clean assembleRelease",
      project_dir: 'android/'
    )

    firebase_app_distribution(
      app: "1:400283721046:android:f4e83d5215fa904b31caf7",
      testers: "ksvivov5@gmail.com",
      android_artifact_type: "APK",
      android_artifact_path: "build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file:"fastlane-example-a1165-40f9d42f5468.json",
      release_notes: "Text of release notes",
      groups: "test",
    )
  end
end

platform :android do
  desc "sends message to slack"
  lane :slack_message do
    slack(
       message: "Testing",
       success: true,
       channel: "#general",
       slack_url: "https://hooks.slack.com/services/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",
       attachment_properties: {
           fields: [
               {
                   title: "message",
                   value: "Sent from fastLane",
               }
           ]
       }
   )

  end
end
